Create a database based on a diagram
OybekKayumov/vet-clinic-db pull request #6
Opened 2022-06-07 12:20 UTC by OybekKayumov

### In this pull request tasks are done:
- Create new tables.
- Convert diagrams and arrows connections into tables.
- Use Many to Many relationships.

## File added
`schema_based_on_diagram.sql`

2022-06-07 15:14 UTC, gemmen29 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 💯 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 15:14 UTC, gemmen29 commented on schema_based_on_diagram.sql
> +);
- [ ] Please add indexes for all foreign keys as in the requirement in order to make the search with foreign keys faster.
![image](https://user-images.githubusercontent.com/24703171/172416645-6072c7e7-1bb0-4460-8690-5eae3113eca7.png)

2022-06-07 16:23 UTC, ShadyShawkat requested changes
## Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![Image](https://c.tenor.com/CWrSBML0hC8AAAAC/little-dinosaur-so-close.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-07 16:23 UTC, ShadyShawkat commented on schema_based_on_diagram.sql
> +  FOREIGN KEY (patient_id) REFERENCES patients(id);
- [ ] Kindly add the indices for the rest of the foreign keys, as suggested by the previous reviewer.

2022-06-08 02:54 UTC, OybekKayumov commented on schema_based_on_diagram.sql
> +  FOREIGN KEY (patient_id) REFERENCES patients(id);
Thank you for your feedback. All indexes were created.

2022-06-08 04:11 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @OybekKayumov, @keza681 👋🏻, 

Good job on making the requested changes 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

![rosycheeks-mochi-peach](https://user-images.githubusercontent.com/4247740/172529240-4be4c1b5-9e1b-425d-96d1-eba07ce02f27.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-08 04:11 UTC, Cathella commented on schema_based_on_diagram.sql
> +CREATE INDEX medical_histories_patient_id_idx ON medical_histories(patient_id);
✅ Added indexes 👍🏻

2022-06-08 10:48 UTC, merged